### ISSUE TITLE
Run eDQL via a batch file

### ISSUE THREAD

**Issue by AraxesTharsis** [parag4u/eDQL#3]
I'm trying to run eDQL from a Windows environment where there are several JREs, and I can't change the default one, so I need to be able to launch the tool from a batch file pointing to the correct JRE. Unfortunately, all attempts end with the error: "_No JVM could be found on your system. Please define EXE4J_JAVA_HOME_" (see image). I tried both JRE 18 and 11 with the same result:

![eDQL Error](https://user-images.githubusercontent.com/11651500/176862677-646407f7-4b54-4432-81bd-fc15f0e93263.png)

**Comment by parag4u** [comment]
Sorry for late response. Please use attached batch for this option. I will add batch in next releases in case anyone wants to use it
[eDQL.bat.txt](https://github.com/parag4u/eDQL/files/9191645/eDQL.bat.txt)
.
